Wi 227281
Flexberry/NewPlatform.Flexberry.AppMetrics pull request #1
Opened 2022-05-20 13:36 UTC by FCherepanov

[#227281 Пакеты для интеграции метрик в приложения Owin](https://github.com/Flexberry/NewPlatform.Flexberry.AppMetrics/commit/f7459192bca72bc7723392fa901e1d147febf328)

2022-05-24 06:16 UTC, bratchikov requested changes

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin.Core/NewPlatform.Flexberry.AppMetrics.Owin.Core.csproj
> +  </PropertyGroup>
Если зависимости позволяют, то давай добавим key.snk и подпишем все эти сборки. Иначе какой-нибудь прикладной проект получит сюрприз, если потребуется подписать прикладные сборки.

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin.Unity/DependencyInjection/OwinMetricsUnityExtensions.cs
> +using Unity;
using-и вылезли наружу

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/AppMetricsMiddleware.cs
> +using System.Threading.Tasks;
Опять юзинги вылезли наружу.
Добавь Flexberry.ruleset из ORM для Analysers.

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/AppMetricsMiddleware.cs
> +        protected AppMetricsMiddleware(TOptions options, IMetrics metrics)
Пропущен XML-комментарий.

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/AppMetricsMiddleware.cs
> +        protected virtual void MiddlewareExecuted()
Пропущен XML-комментарий.

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/AppMetricsMiddleware.cs
> +        protected virtual void MiddlewareExecuting()
Пропущен XML-комментарий.

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/AppMetricsMiddleware.cs
> +        protected Task WriteResponseAsync(IDictionary<string, object> environment, string content, string contentType,
Пропущен XML-комментарий.

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/PerRequestTimerMiddleware.cs
> +        public async Task Invoke(IDictionary<string, object> environment)
Пропущен XML-комментарий.

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/PerRequestTimerMiddleware.cs
> +        protected override bool ShouldPerformMetric(IDictionary<string, object> environment)
Пропущен XML-комментарий.

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/PingEndpointMiddleware.cs
> +        public async Task Invoke(IDictionary<string, object> environment)
Пропущен XML-комментарий.

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/PostAndPutRequestSizeHistogramMiddleware.cs
> +        public async Task Invoke(IDictionary<string, object> environment)
Пропущен XML-комментарий.

2022-05-24 06:16 UTC, bratchikov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/RequestTimerMiddleware.cs
> +        public async Task Invoke(IDictionary<string, object> environment)
Пропущен XML-комментарий.

2022-05-24 12:21 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin.Core/NewPlatform.Flexberry.AppMetrics.Owin.Core.csproj
> +  </PropertyGroup>
Добавил.

2022-05-24 12:22 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin.Unity/DependencyInjection/OwinMetricsUnityExtensions.cs
> +using Unity;
Это из-за Owin и Unity в пространстве имен сбоки. Можно использовать global::, но я решил вынести.

2022-05-24 12:23 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/AppMetricsMiddleware.cs
> +using System.Threading.Tasks;
Это из-за псевдонима `using AppFunc = Func<IDictionary<string, object>, Task>;` Analysers добавил.

2022-05-24 12:33 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/AppMetricsMiddleware.cs
> +        protected AppMetricsMiddleware(TOptions options, IMetrics metrics)
Добавил.

2022-05-24 12:33 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/AppMetricsMiddleware.cs
> +        protected virtual void MiddlewareExecuted()
Добавил.

2022-05-24 12:33 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/AppMetricsMiddleware.cs
> +        protected virtual void MiddlewareExecuting()
Добавил.

2022-05-24 12:33 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/AppMetricsMiddleware.cs
> +        protected Task WriteResponseAsync(IDictionary<string, object> environment, string content, string contentType,
Добавил.

2022-05-24 12:33 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/PerRequestTimerMiddleware.cs
> +        public async Task Invoke(IDictionary<string, object> environment)
Добавил.

2022-05-24 12:33 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/PerRequestTimerMiddleware.cs
> +        protected override bool ShouldPerformMetric(IDictionary<string, object> environment)
Добавил.

2022-05-24 12:33 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/PingEndpointMiddleware.cs
> +        public async Task Invoke(IDictionary<string, object> environment)
Добавил.

2022-05-24 12:33 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/RequestTimerMiddleware.cs
> +        public async Task Invoke(IDictionary<string, object> environment)
Добавил.

2022-05-24 12:33 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/PostAndPutRequestSizeHistogramMiddleware.cs
> +        public async Task Invoke(IDictionary<string, object> environment)
Добавил.

2022-05-24 12:44 UTC, bratchikov approved these changes

2022-05-24 12:45 UTC, merged

2022-06-15 06:38 UTC, mao29 commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/ApdexMiddleware.cs
> +                using (apdex as IDisposable)
А это зачем так?

2022-06-15 06:41 UTC, FCherepanov commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/ApdexMiddleware.cs
> +                using (apdex as IDisposable)
НЗ - этот кусок из интеграции взят. Но мне кажется это хитрый способ задиспозить объект если он вдруг IDisposable.

2022-06-16 07:16 UTC, mao29 commented on src/NewPlatform.Flexberry.AppMetrics.Owin/Middleware/ApdexMiddleware.cs
> +                using (apdex as IDisposable)
Ок